import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar/Navbar'
import SocialMediaButton from '@/components/SpeedDial/SpeedDialComponent'
import { FooterWithSocialLinks } from '@/components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Cristal Sarabia',
  description: 'Generated by create next app',
} 

export default function RootLayout({ children }) {

   
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-visible`}>
       
        <header className={`sticky top-0 z-50`} > 
          <Navbar/>   
        </header>
       
        <SocialMediaButton/>
     
        {children}  
           
        <footer >
          <FooterWithSocialLinks/>
        </footer>
        
      </body>
    </html>
  )
}
